### ISSUE TITLE
carriage return (\n) are removed when it is displayed on the webpage

### ISSUE THREAD

**Issue by chrisagon** [riccardolinares/unChatGPT#1]
The carriage return are present in the json file from openai. But when it is displayed on the webpage in the div message-bot, all the '\n' seems to be removed. So I have a block of text without paragraph...

In the json : 
```
...
 completion: '\n' +
    '\n' +
    'Verse 1:\n' +
    "J'ai cherché partout pour trouver ma force,\n" +
    'Je ne me sentais pas assez fort.\n' +
    "Je me sentais si seul, je pensais que je ne pourrais jamais m'en sortir,\n" +
...
```
on the div *message-bot* we have the carriage return ([CR][LF] or '\r\n', I see them with dev-tools.
```
...
Verse 1:
J'ai cherché partout pour trouver ma force,
Je ne me sentais pas assez fort.
Je me sentais si seul, je pensais que je ne pourrais jamais m'en sortir,
...
```
But when it is displayed on the webpage, it is a block of text 
there must be a problem in the display of the div block *message-bot* , maybe in its definition in css, which causes this display without paragraph.
I am not sure but maybe we have to add **whitespace-pre-wrap** in the tailwind CSS, but I don't know how....

**Comment by riccardolinares** [comment]
@chrisagon thanks for your suggestion, we added it in the div! The problem was also in the openai api route. Now the breakline are properly shown. You can now pull and use unChatGPT :)
