### ISSUE TITLE
Model gpt-3.5-turbo make an error request failed with status 404

### ISSUE THREAD

**Issue by chrisagon** [riccardolinares/unChatGPT#2]
I would migrate to "gpt-3.5-turbo" from "text-davinci-003"but I have an error.
Error: Request failed with status code 404
    at createError (/home/freebox/unChatGPT/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/freebox/unChatGPT/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/freebox/unChatGPT/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 

When I come back to "text-davinci-003" I have no error.
May be it is because "text-davinci-003" is for text_completion and "gpt-3.5-turbo" is for chat.completion and the structure of messages are differents.

  ```
id: 'cmpl-6rZ2skyOH0hwaIqwRB3p4sSbbjx7C',
  object: 'text_completion',
  created: 1678224118,
  model: 'text-davinci-003',
  choices: [
    {
      text: '\n\nCeci est un test.',
      index: 0,
      logprobs: null,
      finish_reason: 'stop'
    }
  ],
  usage: { prompt_tokens: 18, completion_tokens: 9, total_tokens: 27 }
}
{
  value: 'undefined agir comme un testeur et dire "ceci est un test".',
  completion: '\\n\\nCeci est un test.'
```

```
{
 'id': 'chatcmpl-6p9XYPYSTTRi0xEviKjjilqrWU2Ve',
 'object': 'chat.completion',
 'created': 1677649420,
 'model': 'gpt-3.5-turbo',
 'usage': {'prompt_tokens': 56, 'completion_tokens': 31, 'total_tokens': 87},
 'choices': [
   {
    'message': {
      'role': 'assistant',
      'content': 'The 2020 World Series was played in Arlington, Texas at the Globe Life Field, which was the new home stadium for the Texas Rangers.'},
    'finish_reason': 'stop',
    'index': 0
   }
  ]
}```

UnChatGPT is not ready for chat.completion.

**Comment by riccardolinares** [comment]
Hi. Thanks for the report. I modified the code to make it work with gpt-3.5-turbo as well. You have to update the version of OpenAI in the package.json for it to work correctly. I also added a variable in the .env file for the price of each token.

Let me know if it works properly on your side :)


Check this commit on the repo: https://github.com/riccardolinares/unChatGPT/commit/c51cf91013528db01a453759eb28362293c70755

**Comment by chrisagon** [comment]
Sorry, but I have commited and updated my node app : I have exactly the same error :-/

**Comment by riccardolinares** [comment]
Did you make a pull requests of the repo? 

Can you try to clone the repo in a new folder, edit the new version of the .env file and run the script again? 

Please let me know 🙂

**Comment by chrisagon** [comment]
Yes I have cloned directly your repository on my VM to be sure the problem was not from my fork.

**Comment by chrisagon** [comment]
The problem seems to come from my VM or linux version. 
It is OK on windows and on a VPS with linux.

**Comment by chrisagon** [comment]
I try on another linux distro (ubuntu instead of debian) and I have the same error. 
The problem must come from the architecture of the server. 
It works on AMD64 but it does not work on ARM64...
